### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by ruotongyu** [dhuertas/ann#1]
Hello, I am trying to follow your instruction and run the neural network. 
Here is the console output:
_g++   -o ann
g++: fatal error: no input files
compilation terminated.
Makefile:23: recipe for target 'ann' failed
make: *** [ann] Error 1_

I also tried to compile by gcc without makefile
The other output is here: 
In file included from main.cpp:9:0:
_Utils.hh: In function ‘void vector2double(std::vector<std::__cxx11::basic_string<char> >&, std::vector<double>&)’:
Utils.hh:22:31: error: cannot convert ‘std::__cxx11::basic_string<char>’ to ‘const char*’ for argument ‘1’ to ‘double strtod(const char*, char**)’
     out.push_back(strtod(in[i]));
                               ^
main.cpp: In function ‘void getArguments(int, char**)’:
main.cpp:45:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (unsigned i = 1; i < argc; ++i) {
                          ^
main.cpp:50:48: error: ‘stoul’ was not declared in this scope
         options.topology.push_back(stoul(tmp[i]));
                                                ^
main.cpp:55:39: error: too few arguments to function ‘double strtod(const char*, char**)’
       options.alpha = strtod(argv[++i]);
                                       ^
In file included from main.cpp:7:0:
/usr/include/stdlib.h:164:15: note: declared here
 extern double strtod (const char *__restrict __nptr,
               ^
main.cpp:57:37: error: too few arguments to function ‘double strtod(const char*, char**)’
       options.eta = strtod(argv[++i]);
                                     ^
In file included from main.cpp:7:0:
/usr/include/stdlib.h:164:15: note: declared here
 extern double strtod (const char *__restrict __nptr,
               ^
main.cpp: In function ‘int main(int, char**)’:
main.cpp:123:44: error: cannot convert ‘std::__cxx11::basic_string<char>’ to ‘const char*’ for argument ‘1’ to ‘double strtod(const char*, char**)’
         inputValues.push_back(strtod(csv[i]));
                                            ^
main.cpp:125:45: error: cannot convert ‘std::__cxx11::basic_string<char>’ to ‘const char*’ for argument ‘1’ to ‘double strtod(const char*, char**)’
         targetValues.push_back(strtod(csv[i]));
                                             ^
main.cpp:178:42: error: cannot convert ‘std::__cxx11::basic_string<char>’ to ‘const char*’ for argument ‘1’ to ‘double strtod(const char*, char**)’
       inputValues.push_back(strtod(csv[i]));_

I am not quite sure if I missed something important?

Really appreciate your help!!

**Comment by dhuertas** [comment]
Hi,

Check that you have all the necessary tools to compile the code. In particular, check for `g++`.

Here's my `make` and `g++ -v` output as of today:

```
dani@TARS:~/Code/ann$ git pull
Already up-to-date.
dani@TARS:~/Code/ann$ make
gcc -c -g -std=c++11 -Wall -O3 -I./src src/Network.cc -o src/Network.o
gcc -MM -g -std=c++11 -Wall -O3 -I./src src/Network.cc > src/Network.d
gcc -c -g -std=c++11 -Wall -O3 -I./src src/Neuron.cc -o src/Neuron.o
gcc -MM -g -std=c++11 -Wall -O3 -I./src src/Neuron.cc > src/Neuron.d
gcc -c -g -std=c++11 -Wall -O3 -I./src src/main.cc -o src/main.o
gcc -MM -g -std=c++11 -Wall -O3 -I./src src/main.cc > src/main.d
g++ ./src/Network.o ./src/Neuron.o ./src/main.o  -o ann
dani@TARS:~/Code/ann$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.4' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4)```
